"""
Demo / test data seeder for Hotel PMS.

All records created here are marked with is_test_data = 1 and can be
removed safely by calling delete_test_data().

Reservations cover June, July, August, September and October 2026
(arrivals from 1 June, departures no later than 1 November). The calendar
is generated by a seeded random generator, so every run produces the same
reservations (same ids, same rooms, same dates) and re-running skips the
ones that already exist. No room is ever booked twice on the same night.

Statuses depend on the day the seeder runs:
  departure <= today            → Completed   (a few Cancelled / No Show)
  arrival <= today < departure  → Checked In
  arrival > today               → Confirmed   (a few Draft / Cancelled)
"""

import random
from datetime import date, timedelta

import frappe
from frappe.utils import nowdate, getdate


# ─── Calendar & volume settings ───────────────────────────────────────────────

SEASON_START = date(2026, 6, 1)    # first arrival
SEASON_END = date(2026, 10, 31)    # last arrival
LAST_DEPARTURE = date(2026, 11, 1) # stays never run past this checkout day
RANDOM_SEED = 2026                 # change it to get a different (still fixed) calendar

# Arrivals tried per day (min, max). More in July/August.
ARRIVALS_PER_DAY = {6: (1, 3), 7: (2, 4), 8: (2, 4), 9: (1, 3), 10: (1, 3)}

# Room price multiplier per month
SEASON_MULTIPLIER = {6: 1.10, 7: 1.25, 8: 1.30, 9: 1.10, 10: 1.00}


# ─── Reference data (shared by the creators and the reservation plan) ─────────

ROOM_TYPES = [
    {"room_type": "Standard Room", "code": "STD", "capacity_adults": 2, "capacity_children": 1, "maximum_occupancy": 3, "base_price": 800},
    {"room_type": "Deluxe Room", "code": "DLX", "capacity_adults": 2, "capacity_children": 2, "maximum_occupancy": 4, "base_price": 1200},
    {"room_type": "Suite", "code": "STE", "capacity_adults": 2, "capacity_children": 2, "maximum_occupancy": 4, "base_price": 2000},
    {"room_type": "Family Room", "code": "FAM", "capacity_adults": 2, "capacity_children": 3, "maximum_occupancy": 5, "base_price": 1600},
]
BASE_PRICE = {rt["room_type"]: rt["base_price"] for rt in ROOM_TYPES}


def _rooms_data():
    rooms = []
    for i in range(1, 6):   # Floor 1: Standard 101-105
        rooms.append({"room_number": f"10{i}", "room_type": "Standard Room", "floor": "1", "capacity": 2})
    for i in range(1, 6):   # Floor 2: Deluxe 201-205
        rooms.append({"room_number": f"20{i}", "room_type": "Deluxe Room", "floor": "2", "capacity": 3})
    for i in range(1, 4):   # Floor 3: Suites 301-303
        rooms.append({"room_number": f"30{i}", "room_type": "Suite", "floor": "3", "capacity": 4})
    for i in range(1, 7):   # Floor 4: Family 401-406
        rooms.append({"room_number": f"40{i}", "room_type": "Family Room", "floor": "4", "capacity": 5})
    return rooms


ROOMS = _rooms_data()

BASE_CUSTOMERS = [
    {"first_name": "Ahmed", "last_name": "Benali", "phone": "+213-555-0001", "email": "ahmed.benali@email.com", "nationality": "Algerian", "customer_category": "Individual"},
    {"first_name": "Fatima", "last_name": "Cherif", "phone": "+213-555-0002", "email": "fatima.cherif@email.com", "nationality": "Algerian", "customer_category": "Family"},
    {"first_name": "Mohammed", "last_name": "Saidi", "phone": "+213-555-0003", "email": "m.saidi@corp.com", "nationality": "Algerian", "customer_category": "Corporate"},
    {"first_name": "Sarah", "last_name": "Johnson", "phone": "+1-555-0004", "email": "sarah.j@email.com", "nationality": "American", "customer_category": "VIP"},
    {"first_name": "Pierre", "last_name": "Dupont", "phone": "+33-555-0005", "email": "p.dupont@email.fr", "nationality": "French", "customer_category": "Individual"},
    {"first_name": "Amina", "last_name": "Boudiaf", "phone": "+213-555-0006", "email": "amina.b@email.com", "nationality": "Algerian", "customer_category": "Family"},
    {"first_name": "Carlos", "last_name": "Martinez", "phone": "+34-555-0007", "email": "c.martinez@email.es", "nationality": "Spanish", "customer_category": "Individual"},
    {"first_name": "Nadia", "last_name": "Rahmani", "phone": "+213-555-0008", "email": "n.rahmani@email.com", "nationality": "Algerian", "customer_category": "VIP"},
    {"first_name": "John", "last_name": "Smith", "phone": "+44-555-0009", "email": "j.smith@email.co.uk", "nationality": "British", "customer_category": "Corporate"},
    {"first_name": "Khadija", "last_name": "Messaoud", "phone": "+213-555-0010", "email": "k.messaoud@email.com", "nationality": "Algerian", "customer_category": "Family"},
    {"first_name": "Liu", "last_name": "Wei", "phone": "+86-555-0011", "email": "liu.wei@email.cn", "nationality": "Chinese", "customer_category": "Group"},
    {"first_name": "Hassan", "last_name": "Otmani", "phone": "+212-555-0012", "email": "h.otmani@email.ma", "nationality": "Moroccan", "customer_category": "Individual"},
    {"first_name": "Marie", "last_name": "Bernard", "phone": "+33-555-0013", "email": "m.bernard@email.fr", "nationality": "French", "customer_category": "Individual"},
    {"first_name": "Omar", "last_name": "Brahim", "phone": "+213-555-0014", "email": "o.Brahim@agency.dz", "nationality": "Algerian", "customer_category": "Agency"},
    {"first_name": "Yasmine", "last_name": "Hamdi", "phone": "+216-555-0015", "email": "y.hamdi@email.tn", "nationality": "Tunisian", "customer_category": "Family"},
]


def _extra_customers(count=45):
    """Fixed list of extra guests (same names and emails on every run)."""
    people = [
        ("Sami", "Trabelsi", "Tunisian", "+216"), ("Leila", "Gharbi", "Tunisian", "+216"),
        ("Karim", "Jaziri", "Tunisian", "+216"), ("Ines", "Mansour", "Tunisian", "+216"),
        ("Walid", "Haddad", "Tunisian", "+216"), ("Rania", "Ayari", "Tunisian", "+216"),
        ("Youssef", "Bouzid", "Algerian", "+213"), ("Lina", "Kaci", "Algerian", "+213"),
        ("Bilal", "Hadjadj", "Algerian", "+213"), ("Sonia", "Ferhat", "Algerian", "+213"),
        ("Mehdi", "Alaoui", "Moroccan", "+212"), ("Salma", "Bennani", "Moroccan", "+212"),
        ("Anas", "Tazi", "Moroccan", "+212"), ("Hiba", "Chraibi", "Moroccan", "+212"),
        ("Julien", "Moreau", "French", "+33"), ("Camille", "Laurent", "French", "+33"),
        ("Thomas", "Girard", "French", "+33"), ("Chloe", "Roux", "French", "+33"),
        ("Lukas", "Muller", "German", "+49"), ("Anna", "Schmidt", "German", "+49"),
        ("Felix", "Weber", "German", "+49"), ("Giulia", "Rossi", "Italian", "+39"),
        ("Marco", "Bianchi", "Italian", "+39"), ("Sofia", "Romano", "Italian", "+39"),
        ("Lucia", "Garcia", "Spanish", "+34"), ("Javier", "Lopez", "Spanish", "+34"),
        ("Emma", "Wilson", "British", "+44"), ("Oliver", "Brown", "British", "+44"),
        ("Ava", "Taylor", "British", "+44"), ("Noah", "Davis", "American", "+1"),
        ("Mia", "Clark", "American", "+1"), ("Daan", "de Vries", "Dutch", "+31"),
        ("Eva", "Jansen", "Dutch", "+31"), ("Mateus", "Silva", "Portuguese", "+351"),
        ("Ana", "Costa", "Portuguese", "+351"), ("Ali", "Hassan", "Egyptian", "+20"),
        ("Mona", "Fahmy", "Egyptian", "+20"), ("Khalid", "Al Mansouri", "Emirati", "+971"),
        ("Noura", "Al Saud", "Saudi", "+966"), ("Ivan", "Petrov", "Russian", "+7"),
        ("Olga", "Ivanova", "Russian", "+7"), ("Kenji", "Sato", "Japanese", "+81"),
        ("Yuki", "Tanaka", "Japanese", "+81"), ("Ahmet", "Yilmaz", "Turkish", "+90"),
        ("Elif", "Kaya", "Turkish", "+90"),
    ]
    categories = ["Individual", "Family", "Individual", "Corporate", "Family", "VIP", "Agency", "Group"]
    out = []
    for i, (first, last, nat, code) in enumerate(people[:count]):
        slug = f"{first}.{last}".lower().replace(" ", "")
        out.append({
            "first_name": first,
            "last_name": last,
            "phone": f"{code}-555-{1100 + i:04d}",
            "email": f"{slug}@test-hotel.com",
            "nationality": nat,
            "customer_category": categories[i % len(categories)],
        })
    return out


CUSTOMERS = BASE_CUSTOMERS + _extra_customers()


# ─── Public entry points ──────────────────────────────────────────────────────

@frappe.whitelist()
def seed():
    """Create all test data. Safe to call multiple times (idempotent)."""
    log = []
    errors = []

    def ok(msg):
        print(msg)
        log.append(msg)

    def run(fn):
        try:
            fn(ok)
            frappe.db.commit()   # keep each finished step even if a later one fails
        except Exception as e:
            msg = f"ERROR in {fn.__name__}: {e}"
            print(msg)
            log.append(msg)
            errors.append(msg)
            frappe.db.rollback()

    run(create_test_room_types)
    run(create_test_rooms)
    run(create_test_services)
    run(create_test_packages)
    run(create_test_customers)
    run(create_test_reservations)
    run(create_test_stays)
    run(create_test_folios)
    run(create_test_payments)
    run(create_test_housekeeping)

    frappe.db.commit()
    ok("=== Test data seeding complete ===")
    return {"log": log, "errors": errors}


@frappe.whitelist()
def delete_test_data():
    """Delete all records where is_test_data = 1, in safe dependency order."""
    log = []

    def ok(msg):
        print(msg)
        log.append(msg)

    # 1. Housekeeping
    _delete_dt("Hotel Housekeeping", ok)

    # 2. Payments
    _delete_dt("Hotel Payment", ok)

    # 3. Folio items (via folio parent)
    folios = frappe.get_all("Hotel Folio", filters={"is_test_data": 1}, pluck="name")
    for f in folios:
        frappe.db.delete("Hotel Folio Item", {"parent": f})
    ok(f"  Deleted folio items for {len(folios)} folios")

    # 4. Folios
    _delete_dt("Hotel Folio", ok)

    # 5. Room movements
    _delete_dt("Hotel Room Movement", ok)

    # 6. Stays
    _delete_dt("Hotel Stay", ok)

    # 7. Reservation child tables
    reservations = frappe.get_all("Hotel Reservation", filters={"is_test_data": 1}, pluck="name")
    for r in reservations:
        frappe.db.delete("Hotel Reservation Room", {"parent": r})
        frappe.db.delete("Hotel Reservation Family", {"parent": r})
        frappe.db.delete("Hotel Reservation Guest", {"parent": r})
    ok(f"  Deleted reservation children for {len(reservations)} reservations")

    # 8. Reservations
    _delete_dt("Hotel Reservation", ok)

    # 9. Package items
    packages = frappe.get_all("Hotel Package", filters={"is_test_data": 1}, pluck="name")
    for p in packages:
        frappe.db.delete("Hotel Package Item", {"parent": p})
    ok(f"  Deleted package items for {len(packages)} packages")

    # 10. Packages
    _delete_dt("Hotel Package", ok)

    # 11. Services
    _delete_dt("Hotel Service", ok)

    # 12. Rooms
    _delete_dt("Hotel Room", ok)

    # 13. Room types
    _delete_dt("Hotel Room Type", ok)

    # 14. Customers
    _delete_dt("Hotel Customer", ok)

    frappe.db.commit()
    ok("=== Test data deletion complete ===")
    return {"log": log}


# ─── Helpers ──────────────────────────────────────────────────────────────────

def _delete_dt(doctype, ok):
    records = frappe.get_all(doctype, filters={"is_test_data": 1}, pluck="name")
    for name in records:
        try:
            frappe.delete_doc(doctype, name, ignore_permissions=True, force=True)
        except Exception:
            frappe.db.delete(doctype, {"name": name})
    ok(f"  Deleted {len(records)} {doctype} records")


def _exists(doctype, name):
    return frappe.db.exists(doctype, name)


def _insert(doc_dict):
    doc = frappe.get_doc(doc_dict)
    doc.insert(ignore_permissions=True)
    return doc


# ─── Room Types ───────────────────────────────────────────────────────────────

def create_test_room_types(ok):
    created = 0
    for rt in ROOM_TYPES:
        if not _exists("Hotel Room Type", rt["room_type"]):
            _insert({"doctype": "Hotel Room Type", **rt, "active": 1, "is_test_data": 1})
            created += 1
    ok(f"  Room Types: {created} created (of {len(ROOM_TYPES)})")


# ─── Rooms ────────────────────────────────────────────────────────────────────

def create_test_rooms(ok):
    created = 0
    for r in ROOMS:
        if not _exists("Hotel Room", r["room_number"]):
            _insert({
                "doctype": "Hotel Room",
                **r,
                "status": "Available",
                "room_name": f"Room {r['room_number']}",
                "housekeeping_status": "Clean",
                "active": 1,
                "is_test_data": 1,
            })
            created += 1
    ok(f"  Rooms: {created} created (of {len(ROOMS)})")


# ─── Services ─────────────────────────────────────────────────────────────────

def create_test_services(ok):
    services = [
        {"service_name": "Breakfast", "code": "BRK", "category": "Food & Beverage", "rate": 120},
        {"service_name": "Half Board", "code": "HB", "category": "Food & Beverage", "rate": 250},
        {"service_name": "Full Board", "code": "FB", "category": "Food & Beverage", "rate": 400},
        {"service_name": "All Inclusive", "code": "AI", "category": "Food & Beverage", "rate": 600},
        {"service_name": "Airport Transfer", "code": "TRNS", "category": "Transport", "rate": 200},
        {"service_name": "Spa Treatment", "code": "SPA", "category": "Wellness", "rate": 350},
        {"service_name": "Laundry Service", "code": "LDY", "category": "Housekeeping", "rate": 80},
        {"service_name": "Horse Riding", "code": "HRS", "category": "Activity", "rate": 300},
        {"service_name": "Extra Bed", "code": "EBD", "category": "Room", "rate": 150},
        {"service_name": "Mini Bar", "code": "MNB", "category": "Food & Beverage", "rate": 50},
    ]
    created = 0
    for s in services:
        if not _exists("Hotel Service", s["service_name"]):
            _insert({"doctype": "Hotel Service", **s, "active": 1, "is_test_data": 1})
            created += 1
    ok(f"  Services: {created} created (of {len(services)})")


# ─── Packages ─────────────────────────────────────────────────────────────────

def create_test_packages(ok):
    pkgs = [
        {
            "package_name": "Bed and Breakfast",
            "code": "BB",
            "description": "Room + daily breakfast",
            "items": [{"service": "Breakfast", "quantity": 1, "rate": 120}],
        },
        {
            "package_name": "Half Board Package",
            "code": "HBP",
            "description": "Room + breakfast + dinner",
            "items": [{"service": "Half Board", "quantity": 1, "rate": 250}],
        },
        {
            "package_name": "Full Board Package",
            "code": "FBP",
            "description": "Room + all meals",
            "items": [{"service": "Full Board", "quantity": 1, "rate": 400}],
        },
        {
            "package_name": "All Inclusive Package",
            "code": "AIP",
            "description": "Room + all meals + activities",
            "items": [
                {"service": "All Inclusive", "quantity": 1, "rate": 600},
                {"service": "Horse Riding", "quantity": 1, "rate": 300},
            ],
        },
        {
            "package_name": "Honeymoon Package",
            "code": "HON",
            "description": "Suite + breakfast + spa",
            "items": [
                {"service": "Breakfast", "quantity": 2, "rate": 120},
                {"service": "Spa Treatment", "quantity": 1, "rate": 350},
            ],
        },
        {
            "package_name": "Family Fun Package",
            "code": "FFP",
            "description": "Family room + activities",
            "items": [
                {"service": "Breakfast", "quantity": 1, "rate": 120},
                {"service": "Horse Riding", "quantity": 2, "rate": 300},
            ],
        },
    ]
    created = 0
    for p in pkgs:
        if not _exists("Hotel Package", p["package_name"]):
            items = p.pop("items", [])
            doc = frappe.get_doc({
                "doctype": "Hotel Package",
                **p,
                "active": 1,
                "is_test_data": 1,
            })
            for item in items:
                item["amount"] = item["quantity"] * item["rate"]
                doc.append("items", item)
            doc.insert(ignore_permissions=True)
            created += 1
    ok(f"  Packages: {created} created (of {len(pkgs)})")


# ─── Customers ────────────────────────────────────────────────────────────────

def create_test_customers(ok):
    created = 0
    for c in CUSTOMERS:
        # Check by email to avoid duplicates
        existing = frappe.db.get_value("Hotel Customer", {"email": c["email"]}, "name")
        if not existing:
            _insert({"doctype": "Hotel Customer", **c, "active": 1, "is_test_data": 1})
            created += 1
    ok(f"  Customers: {created} created (of {len(CUSTOMERS)})")


# ─── Reservation plan (pure Python, no database access) ───────────────────────

def _family_type(adults, children):
    if children:
        return "Large Family" if adults + children >= 6 else "Family"
    return "Single" if adults == 1 else "Couple"


def _guests_for(room_type, rng):
    """(adults, children) that fit the room type's capacity."""
    if room_type == "Standard Room":
        return rng.choice([(1, 0), (2, 0), (2, 0), (2, 1)])
    if room_type == "Deluxe Room":
        return rng.choice([(1, 0), (2, 0), (2, 1), (2, 2)])
    if room_type == "Suite":
        return rng.choice([(2, 0), (2, 0), (2, 1), (2, 2)])
    return rng.choice([(2, 1), (2, 2), (2, 3), (2, 3)])   # Family Room


def _rate_for(room_type, day):
    return int(round(BASE_PRICE[room_type] * SEASON_MULTIPLIER.get(day.month, 1.0) / 10.0) * 10)


def _package_for(room_type, adults, children, rng):
    roll = rng.random()
    if room_type == "Suite" and adults == 2 and not children and roll < 0.55:
        return "Honeymoon Package"
    if room_type == "Family Room" and roll < 0.45:
        return "Family Fun Package"
    if roll < 0.20:
        return "Bed and Breakfast"
    if roll < 0.30:
        return "Half Board Package"
    if roll < 0.36:
        return "Full Board Package"
    if roll < 0.40:
        return "All Inclusive Package"
    return None


def _status_for(arrival, departure, today, roll):
    """Status from the dates, with a few cancellations / no-shows / drafts."""
    if departure <= today:
        if roll < 0.05:
            return "Cancelled"
        if roll < 0.09:
            return "No Show"
        return "Completed"
    if arrival <= today:
        return "Checked In"
    if roll < 0.06:
        return "Cancelled"
    if roll < 0.14:
        return "Draft"
    return "Confirmed"


def build_reservation_plan(today=None):
    """
    Returns the list of reservation scenarios for June–October 2026.

    For every arrival day a few bookings are attempted; each one picks a room type,
    a length of stay and a free room of that type (the checkout day can be the next
    guest's arrival day). Some family bookings take two Family Rooms. If no room of the
    requested type is free, the booking is skipped, as a full hotel would.

    The random numbers are always drawn in the same order, so the calendar and the ids
    do not change from one run to the next; only the statuses follow `today`.
    """
    today = getdate(today or nowdate())
    rng = random.Random(RANDOM_SEED)

    booked = {r["room_number"]: [] for r in ROOMS}          # room -> [(arrival, departure)]
    rooms_by_type = {}
    for r in ROOMS:
        rooms_by_type.setdefault(r["room_type"], []).append(r["room_number"])

    def free_rooms(room_type, start, end):
        return [
            room for room in rooms_by_type[room_type]
            if all(end <= s or start >= e for s, e in booked[room])
        ]

    type_weights = [("Standard Room", 30), ("Deluxe Room", 30), ("Suite", 12), ("Family Room", 28)]
    types, weights = zip(*type_weights)

    plan = []
    seq = 0
    day = SEASON_START
    while day <= SEASON_END:
        lo, hi = ARRIVALS_PER_DAY[day.month]
        for _ in range(rng.randint(lo, hi)):
            # draw every random number first, in a fixed order
            room_type = rng.choices(types, weights)[0]
            nights = rng.choice([2, 3, 3, 4, 4, 5, 5, 6, 7, 7, 10, 14])
            two_rooms_roll = rng.random()
            customer = rng.choice(CUSTOMERS)["email"]
            status_roll = rng.random()
            lead_days = rng.randint(3, 60)
            room_pick = rng.random()
            guests = [_guests_for(room_type, rng) for _ in range(2)]
            package = _package_for(room_type, guests[0][0], guests[0][1], rng)

            departure = min(day + timedelta(days=nights), LAST_DEPARTURE)
            if departure <= day:
                continue

            want = 2 if (room_type == "Family Room" and two_rooms_roll < 0.12) else 1
            free = free_rooms(room_type, day, departure)
            if len(free) < want:
                continue
            start = int(room_pick * len(free))
            chosen = (free[start:] + free[:start])[:want]

            rate = _rate_for(room_type, day)
            rooms = []
            for i, room in enumerate(chosen):
                adults, children = guests[i]
                row = {"room": room, "adults": adults, "rate": rate}
                if children:
                    row["children"] = children
                rooms.append(row)
                booked[room].append((day, departure))

            total_adults = sum(r["adults"] for r in rooms)
            total_children = sum(r.get("children", 0) for r in rooms)
            family = {"family_type": _family_type(total_adults, total_children), "adults": total_adults}
            if total_children:
                family["children"] = total_children

            seq += 1
            plan.append({
                "id": f"S26-{seq:04d}",
                "customer_email": customer,
                "booking_date": min(day - timedelta(days=lead_days), today),
                "arrival": day,
                "departure": departure,
                "status": _status_for(day, departure, today, status_roll),
                "rooms": rooms,
                "families": [family],
                "package": package,
                "room_type": room_type,
            })
        day += timedelta(days=1)

    return plan


# ─── Reservations ─────────────────────────────────────────────────────────────

def _get_customer_by_email(email):
    return frappe.db.get_value("Hotel Customer", {"email": email}, "name")


def create_test_reservations(ok):
    plan = build_reservation_plan()
    customers = {c["email"]: _get_customer_by_email(c["email"]) for c in CUSTOMERS}

    created = 0
    skipped = 0
    by_status = {}
    for s in plan:
        notes = f"Test scenario {s['id']}"
        try:
            customer = customers.get(s["customer_email"])
            if not customer:
                ok(f"    Skipped {s['id']}: customer not found ({s['customer_email']})")
                skipped += 1
                continue

            if frappe.db.exists("Hotel Reservation", {"notes": notes, "is_test_data": 1}):
                skipped += 1
                continue

            doc = frappe.get_doc({
                "doctype": "Hotel Reservation",
                "customer": customer,
                "booking_date": str(s["booking_date"]),
                "arrival_date": str(s["arrival"]),
                "departure_date": str(s["departure"]),
                "status": s["status"],
                "package": s.get("package"),
                "notes": notes,
                "is_test_data": 1,
            })
            for r in s["rooms"]:
                doc.append("rooms", {**r, "room_type": s["room_type"]})
            for f in s["families"]:
                doc.append("families", {
                    **f,
                    "total_guests": f.get("adults", 0) + f.get("children", 0) + f.get("infants", 0),
                })

            doc.flags.ignore_validate = True
            doc.insert(ignore_permissions=True)
            created += 1
            by_status[s["status"]] = by_status.get(s["status"], 0) + 1

            if created % 50 == 0:
                frappe.db.commit()
        except Exception as e:
            frappe.db.rollback()
            ok(f"    Skipped {s['id']}: {e}")
            skipped += 1

    months = {}
    for s in plan:
        key = s["arrival"].strftime("%B")
        months[key] = months.get(key, 0) + 1

    ok(f"  Reservations: {created} created, {skipped} skipped (of {len(plan)} planned)")
    ok("    By arrival month: " + ", ".join(f"{m} {n}" for m, n in months.items()))
    if by_status:
        ok("    By status (created now): " + ", ".join(f"{k} {v}" for k, v in sorted(by_status.items())))


# ─── Stays ────────────────────────────────────────────────────────────────────

def create_test_stays(ok):
    """
    Create stays for:
      - "Completed"   reservations → status "Checked Out" (room Available)
      - "Checked In"  reservations → status "Active"      (room Occupied)
    Completed ones are processed first, so a room in use today ends up Occupied
    even when it also had earlier guests.
    """
    created = 0

    for status_filter, stay_status, room_status in [
        ("Completed",   "Checked Out", "Available"),
        ("Checked In",  "Active",      "Occupied"),
    ]:
        reservations = frappe.get_all(
            "Hotel Reservation",
            filters={"status": status_filter, "is_test_data": 1},
            order_by="arrival_date asc",
            pluck="name",
        )
        for res_name in reservations:
            if frappe.db.count("Hotel Stay", {"reservation": res_name}):
                continue

            res = frappe.get_doc("Hotel Reservation", res_name)
            for res_room in res.rooms:
                stay = frappe.get_doc({
                    "doctype": "Hotel Stay",
                    "customer": res.customer,
                    "reservation": res_name,
                    "room": res_room.room,
                    "checkin_date": f"{res.arrival_date} 14:00:00",
                    "expected_checkout": res.departure_date,
                    "status": stay_status,
                    "is_test_data": 1,
                })
                stay.insert(ignore_permissions=True)
                frappe.db.set_value("Hotel Room", res_room.room, "status", room_status)
                created += 1

            if created and created % 100 == 0:
                frappe.db.commit()

    ok(f"  Stays: {created} created")


# ─── Folios ───────────────────────────────────────────────────────────────────

def create_test_folios(ok):
    """
    Create folios for all stays (Active and Checked Out).
      - Active stays      → status "Open" (partial charges so far)
      - Checked Out stays → status "Paid" (full room charges for all nights)
    Breakfast extras added for variety.
    """
    from frappe.utils import date_diff

    created = 0

    stays = frappe.get_all(
        "Hotel Stay",
        filters={"is_test_data": 1},
        fields=["name", "customer", "reservation", "room", "checkin_date", "expected_checkout", "status"],
    )

    for stay in stays:
        if frappe.db.exists("Hotel Folio", {"stay": stay.name}):
            continue

        # Get room rate from reservation
        rate = 800
        if stay.reservation:
            res_rate = frappe.db.get_value(
                "Hotel Reservation Room",
                {"parent": stay.reservation, "room": stay.room},
                "rate",
            )
            if res_rate:
                rate = res_rate

        checkin_str = getdate(stay.checkin_date).strftime("%Y-%m-%d")
        nights = date_diff(stay.expected_checkout, checkin_str)
        if nights < 1:
            nights = 1

        is_past = stay.status == "Checked Out"
        folio_status = "Open" if not is_past else "Paid"

        folio = frappe.get_doc({
            "doctype": "Hotel Folio",
            "customer": stay.customer,
            "reservation": stay.reservation,
            "stay": stay.name,
            "status": folio_status,
            "is_test_data": 1,
        })

        # Room charge per night
        current_date = getdate(stay.checkin_date)
        for _n in range(nights):
            folio.append("items", {
                "date": str(current_date),
                "charge_type": "Room",
                "description": f"Room charge - {stay.room}",
                "quantity": 1,
                "rate": rate,
                "amount": rate,
                "room": stay.room,
                "is_test_data": 1,
            })
            current_date += timedelta(days=1)

        # Breakfast extras
        breakfast_date = getdate(stay.checkin_date)
        for _n in range(min(nights, 3)):
            folio.append("items", {
                "date": str(breakfast_date),
                "charge_type": "Breakfast",
                "description": "Breakfast × 2 guests",
                "quantity": 2,
                "rate": 120,
                "amount": 240,
                "is_test_data": 1,
            })
            breakfast_date += timedelta(days=1)

        total = sum(i.amount for i in folio.items)
        folio.total_charges = total
        folio.total_payments = total if is_past else 0
        folio.balance = 0 if is_past else total
        folio.insert(ignore_permissions=True)
        created += 1

        if created % 100 == 0:
            frappe.db.commit()

    ok(f"  Folios: {created} created")


# ─── Payments ─────────────────────────────────────────────────────────────────

def create_test_payments(ok):
    """
    Create payments for all folios that have no payment yet:
      - Paid folios (past stays)    → full payment, dated at checkout
      - Open folios (active stays)  → 50 % advance payment, dated today

    Payment dates follow the real checkout dates, so the Revenue Trend chart
    shows June to October 2026.
    """
    METHODS = ["Cash", "Card", "Bank Transfer", "Cash", "Card"]

    created = 0

    folios = frappe.get_all(
        "Hotel Folio",
        filters={"is_test_data": 1},
        fields=["name", "customer", "reservation", "stay", "total_charges", "status"],
    )

    for folio in folios:
        if frappe.db.exists("Hotel Payment", {"folio": folio.name}):
            continue

        total = folio.total_charges or 0
        if total <= 0:
            continue

        is_paid = folio.status == "Paid"

        # Use checkout date for past stays so revenue appears on the correct month
        pay_date = nowdate()
        if is_paid and folio.stay:
            checkout = frappe.db.get_value("Hotel Stay", folio.stay, "expected_checkout")
            if checkout:
                pay_date = str(checkout)

        # Pick payment method deterministically from folio name
        idx = sum(ord(c) for c in folio.name) % len(METHODS)
        method = METHODS[idx]

        if is_paid:
            amount = total
            pay_type = "Full"
            new_folio_status = "Paid"
            remaining = 0.0
        else:
            amount = round(total * 0.5, 2)
            pay_type = "Partial"
            new_folio_status = "Partially Paid"
            remaining = round(total - amount, 2)

        payment = frappe.get_doc({
            "doctype": "Hotel Payment",
            "customer": folio.customer,
            "reservation": folio.reservation,
            "stay": folio.stay,
            "folio": folio.name,
            "payment_date": pay_date,
            "payment_type": pay_type,
            "payment_method": method,
            "amount": amount,
            "is_test_data": 1,
        })
        payment.insert(ignore_permissions=True)

        frappe.db.set_value("Hotel Folio", folio.name, {
            "total_payments": amount,
            "balance": remaining,
            "status": new_folio_status,
        })
        created += 1

        if created % 100 == 0:
            frappe.db.commit()

    ok(f"  Payments: {created} created")


# ─── Housekeeping ─────────────────────────────────────────────────────────────

def create_test_housekeeping(ok):
    # Mark some available rooms as needing cleaning
    rooms = frappe.get_all("Hotel Room",
        filters={"status": "Available", "is_test_data": 1},
        fields=["name", "housekeeping_status"],
        limit=5)

    created = 0
    for room in rooms:
        if frappe.db.exists("Hotel Housekeeping", {"room": room.name, "is_test_data": 1}):
            continue

        hk = frappe.get_doc({
            "doctype": "Hotel Housekeeping",
            "room": room.name,
            "date": nowdate(),
            "previous_status": "Dirty",
            "new_status": "Clean",
            "assigned_to": "Administrator",
            "notes": "Test housekeeping record",
            "is_test_data": 1,
        })
        hk.insert(ignore_permissions=True)
        created += 1

    ok(f"  Housekeeping: {created} created")